"""empty message

Revision ID: f238eb2b6748
Revises: 0553e3ac9411
Create Date: 2019-07-05 19:41:36.951125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f238eb2b6748'
down_revision = '0553e3ac9411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('red', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('color', 'red')
    # ### end Alembic commands ###
